# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Downloads/ad_da_hdmi-master/ad_da_vga/ad_da_vga.srcs/sources_1/ip/sawt_rom/sawt_rom.xci
# IP: The module: 'sawt_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Downloads/ad_da_hdmi-master/ad_da_vga/ad_da_vga.srcs/sources_1/ip/sawt_rom/sawt_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sawt_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/Downloads/ad_da_hdmi-master/ad_da_vga/ad_da_vga.srcs/sources_1/ip/sawt_rom/sawt_rom.xci
# IP: The module: 'sawt_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Downloads/ad_da_hdmi-master/ad_da_vga/ad_da_vga.srcs/sources_1/ip/sawt_rom/sawt_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sawt_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
