# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Downloads/ad_da_hdmi-master/ad_da_vga/ad_da_vga.srcs/sources_1/ip/rom_256x8b/rom_256x8b.xci
# IP: The module: 'rom_256x8b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Downloads/ad_da_hdmi-master/ad_da_vga/ad_da_vga.srcs/sources_1/ip/rom_256x8b/rom_256x8b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_256x8b'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/Downloads/ad_da_hdmi-master/ad_da_vga/ad_da_vga.srcs/sources_1/ip/rom_256x8b/rom_256x8b.xci
# IP: The module: 'rom_256x8b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Downloads/ad_da_hdmi-master/ad_da_vga/ad_da_vga.srcs/sources_1/ip/rom_256x8b/rom_256x8b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_256x8b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
